"""
Extract emotion vectors from cached stories.

Based on Anthropic's methodology:
1. Load stories generated by generate_stories.py
2. Extract activations from mid-late layers
3. Average across tokens and stories
4. Subtract global mean across emotions
5. Project out confounds from neutral corpus

Run from the emoj-poc directory:
    python generate_stories.py  # run this first
    python extract_vectors.py
"""

import torch
import numpy as np
from pathlib import Path
from transformers import AutoModelForCausalLM, AutoTokenizer
from sklearn.decomposition import PCA
import json
from tqdm import tqdm

# -----------------------------------------------------------------------------
# Config
# -----------------------------------------------------------------------------

MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Emotions for alignment (expanded from Anthropic's findings)
EMOTIONS = [
    # Core set (original 6)
    "desperate",
    "calm",
    "hopeful",
    "satisfied",
    "afraid",
    "loving",
    # Extended set - negative/high arousal
    "angry",
    "anxious",
    "frustrated",
    "guilty",
    # Extended set - positive
    "confident",
    "grateful",
    "proud",
    "playful",
    # Extended set - mixed/other
    "surprised",
    "reflective",
    "gloomy",
    "obstinate",
]

DATA_DIR = Path("data")
STORIES_DIR = DATA_DIR / "stories"
VECTORS_DIR = DATA_DIR / "vectors"

# -----------------------------------------------------------------------------
# Load model
# -----------------------------------------------------------------------------

def load_model():
    print(f"Loading {MODEL_NAME}...")
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
        device_map="auto" if DEVICE == "cuda" else None,
    )
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, padding_side="left")
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id

    print(f"Model loaded. Layers: {model.config.num_hidden_layers}, Hidden size: {model.config.hidden_size}")
    return model, tokenizer

# -----------------------------------------------------------------------------
# Load stories (generated by generate_stories.py)
# -----------------------------------------------------------------------------

def load_stories():
    """Load previously generated stories."""
    if not STORIES_DIR.exists():
        raise FileNotFoundError(
            f"Stories directory not found: {STORIES_DIR}\n"
            "Run generate_stories.py first to create the story dataset."
        )

    all_stories = {}
    for emotion in EMOTIONS:
        path = STORIES_DIR / f"{emotion}.json"
        if path.exists():
            with open(path) as f:
                all_stories[emotion] = json.load(f)

    if len(all_stories) < len(EMOTIONS):
        missing = set(EMOTIONS) - set(all_stories.keys())
        raise FileNotFoundError(
            f"Missing stories for emotions: {missing}\n"
            "Run generate_stories.py to generate all stories."
        )

    return all_stories

# -----------------------------------------------------------------------------
# Step 2: Extract activations from stories
# -----------------------------------------------------------------------------

def get_mid_late_layer(model):
    """Get the layer ~2/3 through the model."""
    num_layers = model.config.num_hidden_layers
    return int(num_layers * 0.66)

def extract_activations(model, tokenizer, text, layer):
    """Extract mean activation from a text at specified layer."""

    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(model.device)

    with torch.no_grad():
        outputs = model(**inputs, output_hidden_states=True)

    # Get hidden states at specified layer
    hidden_states = outputs.hidden_states[layer]  # (1, seq_len, hidden_dim)

    # Average across token positions (skip first 10 tokens as setup)
    # Anthropic skips first 50, but our stories are shorter
    start_token = min(10, hidden_states.shape[1] // 2)
    mean_activation = hidden_states[0, start_token:, :].mean(dim=0)  # (hidden_dim,)

    return mean_activation.cpu().float()

def extract_emotion_activations(model, tokenizer, stories):
    """Extract mean activations for each emotion from stories."""

    layer = get_mid_late_layer(model)
    print(f"\nExtracting activations from layer {layer} (mid-late)")

    emotion_activations = {}

    for emotion in EMOTIONS:
        print(f"\nProcessing {emotion}...")
        activations = []

        for item in tqdm(stories[emotion], desc=f"  {emotion}"):
            act = extract_activations(model, tokenizer, item["story"], layer)
            activations.append(act)

        # Stack and average
        stacked = torch.stack(activations)  # (n_stories, hidden_dim)
        emotion_activations[emotion] = stacked.mean(dim=0)  # (hidden_dim,)

        print(f"  Mean activation shape: {emotion_activations[emotion].shape}")

    return emotion_activations

# -----------------------------------------------------------------------------
# Step 3: Compute emotion vectors
# -----------------------------------------------------------------------------

def compute_emotion_vectors(emotion_activations):
    """Compute emotion vectors by subtracting global mean."""

    # Stack all emotion activations
    all_activations = torch.stack(list(emotion_activations.values()))  # (n_emotions, hidden_dim)

    # Compute global mean
    global_mean = all_activations.mean(dim=0)  # (hidden_dim,)

    # Subtract global mean to get emotion vectors
    emotion_vectors = {}
    for emotion, activation in emotion_activations.items():
        emotion_vectors[emotion] = activation - global_mean

    return emotion_vectors, global_mean

# -----------------------------------------------------------------------------
# Step 4: Project out confounds (optional but recommended)
# -----------------------------------------------------------------------------

def generate_neutral_texts():
    """Generate or return neutral texts for confound removal."""
    # Simple neutral texts - could be expanded
    neutral_texts = [
        "The table is made of wood.",
        "Water boils at 100 degrees Celsius.",
        "The document contains five pages.",
        "The meeting is scheduled for Tuesday.",
        "The package arrived yesterday.",
        "The file has been uploaded.",
        "The report includes three sections.",
        "The building has ten floors.",
        "The process takes approximately two hours.",
        "The system requires an update.",
        "The folder contains multiple files.",
        "The instructions are on page four.",
        "The deadline is next week.",
        "The server is located downtown.",
        "The manual explains the procedure.",
        "The form needs to be signed.",
        "The data has been processed.",
        "The schedule shows the timeline.",
        "The list includes twenty items.",
        "The chart displays the results.",
    ]
    return neutral_texts

def extract_neutral_activations(model, tokenizer, neutral_texts, layer):
    """Extract activations from neutral texts."""

    activations = []
    for text in tqdm(neutral_texts, desc="Extracting neutral activations"):
        act = extract_activations(model, tokenizer, text, layer)
        activations.append(act)

    return torch.stack(activations)  # (n_texts, hidden_dim)

def project_out_confounds(emotion_vectors, neutral_activations, variance_threshold=0.5):
    """Project out top PCs of neutral activations from emotion vectors."""

    print(f"\nProjecting out confounds (variance threshold: {variance_threshold})")

    # Fit PCA on neutral activations
    neutral_np = neutral_activations.numpy()

    # Find how many components explain the threshold variance
    pca_full = PCA().fit(neutral_np)
    cumvar = np.cumsum(pca_full.explained_variance_ratio_)
    n_components = np.argmax(cumvar >= variance_threshold) + 1
    n_components = max(1, min(n_components, len(neutral_np) - 1))

    print(f"  Using {n_components} components (explaining {cumvar[n_components-1]:.1%} variance)")

    pca = PCA(n_components=n_components).fit(neutral_np)
    confound_directions = torch.tensor(pca.components_, dtype=torch.float32)  # (n_components, hidden_dim)

    # Project confounds out of each emotion vector
    cleaned_vectors = {}
    for emotion, vector in emotion_vectors.items():
        cleaned = vector.clone()
        for direction in confound_directions:
            # Project out this direction
            projection = (cleaned @ direction) * direction
            cleaned = cleaned - projection
        cleaned_vectors[emotion] = cleaned

    return cleaned_vectors

# -----------------------------------------------------------------------------
# Step 5: Save vectors
# -----------------------------------------------------------------------------

def save_all_data(
    emotion_activations,
    emotion_vectors,
    cleaned_vectors,
    global_mean,
    neutral_activations,
    model_name,
    layer
):
    """Save all intermediate results to disk."""

    VECTORS_DIR.mkdir(parents=True, exist_ok=True)

    # 1. Raw emotion activations (before subtracting mean)
    activations_np = {emotion: act.numpy() for emotion, act in emotion_activations.items()}
    np.savez(
        VECTORS_DIR / "emotion_activations.npz",
        **{f"act_{e}": v for e, v in activations_np.items()},
    )
    print(f"  Saved emotion_activations.npz")

    # 2. Emotion vectors (after subtracting global mean, before confound removal)
    vectors_np = {emotion: vec.numpy() for emotion, vec in emotion_vectors.items()}
    np.savez(
        VECTORS_DIR / "emotion_vectors_raw.npz",
        **{f"vec_{e}": v for e, v in vectors_np.items()},
        global_mean=global_mean.numpy(),
    )
    print(f"  Saved emotion_vectors_raw.npz")

    # 3. Cleaned emotion vectors (after confound removal)
    cleaned_np = {emotion: vec.numpy() for emotion, vec in cleaned_vectors.items()}
    np.savez(
        VECTORS_DIR / "emotion_vectors_cleaned.npz",
        **{f"vec_{e}": v for e, v in cleaned_np.items()},
    )
    print(f"  Saved emotion_vectors_cleaned.npz")

    # 4. Neutral activations (for reference)
    np.savez(
        VECTORS_DIR / "neutral_activations.npz",
        activations=neutral_activations.numpy(),
    )
    print(f"  Saved neutral_activations.npz")

    # 5. Metadata
    metadata = {
        "model_name": model_name,
        "layer": layer,
        "emotions": list(emotion_vectors.keys()),
        "hidden_dim": int(global_mean.shape[0]),
        "n_neutral_texts": int(neutral_activations.shape[0]),
    }
    with open(VECTORS_DIR / "metadata.json", "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"  Saved metadata.json")

    print(f"\nAll data saved to {VECTORS_DIR}")

def load_vectors():
    """Load previously saved emotion vectors."""

    data = np.load(VECTORS_DIR / "emotion_vectors.npz")
    with open(VECTORS_DIR / "metadata.json") as f:
        metadata = json.load(f)

    emotion_vectors = {}
    for emotion in metadata["emotions"]:
        emotion_vectors[emotion] = torch.tensor(data[f"vec_{emotion}"])

    global_mean = torch.tensor(data["global_mean"])

    return emotion_vectors, global_mean, metadata

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

def main():
    # Create directories
    DATA_DIR.mkdir(exist_ok=True)

    # Load model
    model, tokenizer = load_model()
    layer = get_mid_late_layer(model)

    # Step 1: Load stories (must be generated first via generate_stories.py)
    print("\nLoading stories...")
    stories = load_stories()
    print(f"Loaded stories for {len(stories)} emotions")

    # Step 2: Extract activations
    emotion_activations = extract_emotion_activations(model, tokenizer, stories)

    # Step 3: Compute emotion vectors
    emotion_vectors, global_mean = compute_emotion_vectors(emotion_activations)

    print("\nEmotion vectors computed:")
    for emotion, vec in emotion_vectors.items():
        print(f"  {emotion}: norm = {vec.norm():.4f}")

    # Step 4: Project out confounds
    neutral_texts = generate_neutral_texts()
    neutral_activations = extract_neutral_activations(model, tokenizer, neutral_texts, layer)
    cleaned_vectors = project_out_confounds(emotion_vectors, neutral_activations)

    print("\nCleaned emotion vectors:")
    for emotion, vec in cleaned_vectors.items():
        print(f"  {emotion}: norm = {vec.norm():.4f}")

    # Step 5: Save all data
    save_all_data(
        emotion_activations,
        emotion_vectors,
        cleaned_vectors,
        global_mean,
        neutral_activations,
        MODEL_NAME,
        layer
    )

    # Quick validation: check cosine similarities
    print("\n" + "="*60)
    print("Cosine similarities between emotion vectors:")
    print("="*60)

    emotions_list = list(cleaned_vectors.keys())
    for i, e1 in enumerate(emotions_list):
        for e2 in emotions_list[i+1:]:
            v1 = cleaned_vectors[e1]
            v2 = cleaned_vectors[e2]
            cos_sim = (v1 @ v2) / (v1.norm() * v2.norm())
            print(f"  {e1:12} vs {e2:12}: {cos_sim:.3f}")

    print("\nDone! Vectors saved to data/vectors/")

if __name__ == "__main__":
    main()
